version: '3.7'
 
services:
  db-chat:
    image: mariadb
    restart: always
    healthcheck:
      test: "/usr/bin/mysql --user=svdonation --password=svdonation --execute \"SHOW DATABASES;\""
      # test: "/usr/local/mysql/bin/mysql --user=foo --password=foo --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 5
    ports:
      - "3307:3306"
    container_name : db-chat
    environment:
      - MYSQL_ROOT_PASSWORD=nexcore
      - MYSQL_DATABASE=intensive
      - MYSQL_USER=intensive
      - MYSQL_PASSWORD=intensive
      - TZ=Asia/Seoul
    volumes:
      - /apps/intensive/chat/mariadb/data:/var/lib/mysql
      - /apps/intensive/chat/mariadb/conf.d:/etc/mysql/conf.d
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    
  intensive-chat:
    image: iij57/intensive-chat:1.0
    restart: always
    container_name : intensive-chat
    environment:
      - MYSQL_URL=db-chat
      - MYSQL_PORT=3307
      - MYSQL_DATABASE=intensive
      - MYSQL_USER=intensive
      - MYSQL_PASSWORD=intensive
      - TZ=Asia/Seoul
    ports:
      - "8081:8080"
    depends_on:
      - db-chat