
node {

    try{
       stage('Preparation') {
	         dir("/apps/files/workspaces"){
            	git branch: "master", url: 'https://github.com/iij57/intensive-chat.git'
            }
        }
        
        stage('Build') {
         	dir("/apps/files/workspaces/intensive-chat"){
            	sh "mvn clean package"
            }
        }        

        stage('make') {
            dir("/apps/files/workspaces/intensive-chat"){
                  	sh "cp ./target/intensive-chat-1.0-SNAPSHOT.jar src/main/docker/"
            }
            dir("/apps/files/workspaces/intensive-chat/src/main/docker"){
                   	sh "docker build -t iij57/intensive-chat:1.0 -t iij57/intensive-chat:latest . "
            }
        }
        
        stage('push') {

        }
        stage('run'){
        	dir("/apps/files/workspaces/intensive-chat/src/main/docker"){
        		sh "docker-compose up -d"
        	}
        }
        currentResult = 'SUCCESS'
    } catch (exec){
        currentResult = 'FAILURE'
        echo(" exception : " + exec)
        throw exec
    } finally {
    	dir("/apps/files/workspaces/intensive-chat"){
        	archiveArtifacts artifacts: 'target/*.jar', onlyIfSuccessful: true, fingerprint: true
       	}
        def color = "good"
        if(currentResult != "SUCCESS"){
            color = "bad"
        }
      
    }
}